// src/config/eventTypes.js

export const EVENT_TYPES = {
  // Customer

  USER_REGISTERED: "USER_REGISTERED",

  ORDER_CREATED: "ORDER_CREATED",

  ORDER_PACKED: "ORDER_PACKED",

  ORDER_SHIPPED: "ORDER_SHIPPED",

  ORDER_OUT_FOR_DELIVERY:
    "ORDER_OUT_FOR_DELIVERY",

  ORDER_DELIVERED: "ORDER_DELIVERED",

  ORDER_CANCELLED: "ORDER_CANCELLED",

  FEEDBACK_REQUEST: "FEEDBACK_REQUEST",

  CART_ABANDONED: "CART_ABANDONED",

  PROMO_CAMPAIGN: "PROMO_CAMPAIGN",

  NEW_DROP_ALERT: "NEW_DROP_ALERT",

  // Returns & Refunds

  RETURN_REQUESTED:
    "RETURN_REQUESTED",

  RETURN_PICKUP_SCHEDULED:
    "RETURN_PICKUP_SCHEDULED",

  RETURN_RECEIVED:
    "RETURN_RECEIVED",

  REFUND_INITIATED:
    "REFUND_INITIATED",

  REFUND_PROCESSED:
    "REFUND_PROCESSED",

  // Inventory

  LOW_STOCK: "LOW_STOCK",

  OUT_OF_STOCK: "OUT_OF_STOCK",

  // Reports

  DAILY_REPORT: "DAILY_REPORT",

  WEEKLY_REPORT: "WEEKLY_REPORT",

  MONTHLY_REPORT: "MONTHLY_REPORT",

  // Platform

  SYSTEM_ERROR: "SYSTEM_ERROR",
};
